/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RestockForm.java
 *
 * Created on 22-Oct-2013, 14:21:54
 */

/**
 *
 * @author fennell.38261
 */
public class RestockForm extends javax.swing.JFrame {

   public static int GunToRestock1=10;//This is a variable created to be used in the restock form.
   public static int GunToRestock2=10;//This is a variable created to be used in the restock form.
   public static int GunToRestock3=10;//This is a variable created to be used in the restock form.
   public static int GunToRestock4=10;//This is a variable created to be used in the restock form.
   public static int GunToRestock5=10;//This is a variable created to be used in the restock form.
   public static int GunToRestock6=10;//This is a variable created to be used in the restock form.
   public static int CoinToRestock1=10;//This is a variable created to be used in the restock form.
   public static int CoinToRestock2=10;//This is a variable created to be used in the restock form.
   public static int CoinToRestock3=10;//This is a variable created to be used in the restock form.
   public static int CoinToRestock4=10;//This is a variable created to be used in the restock form.
   public static int CoinToRestock5=10;//This is a variable created to be used in the restock form.


/** Creates new form RestockForm */
    public RestockForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RestockButton = new javax.swing.JButton();
        StockFrameGun1 = new javax.swing.JTextField();
        StockFrameGun2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StockFrameGun3 = new javax.swing.JTextField();
        StockFrameGun4 = new javax.swing.JTextField();
        StockFrameGun5 = new javax.swing.JTextField();
        StockFrameGun6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        StockFrameCoin1 = new javax.swing.JTextField();
        StockFrameCoin2 = new javax.swing.JTextField();
        StockFrameCoin3 = new javax.swing.JTextField();
        StockFrameCoin4 = new javax.swing.JTextField();
        StockFrameCoin5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        RestockButton.setText("Restock");
        RestockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestockButtonActionPerformed(evt);
            }
        });

        StockFrameGun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockFrameGun1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gun1");

        jLabel2.setText("Gun2");

        jLabel3.setText("Gun3");

        jLabel4.setText("Gun4");

        jLabel5.setText("Gun5");

        jLabel6.setText("Gun6");

        jLabel9.setText("50 Cent");

        jLabel10.setText("20 Cent");

        jLabel11.setText("10 Cent");

        StockFrameCoin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockFrameCoin1ActionPerformed(evt);
            }
        });

        StockFrameCoin5.setText("0");

        jLabel7.setText("2 Euro");

        jLabel8.setText("1 Euro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(StockFrameGun6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameGun5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameGun4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameGun3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameGun2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameGun1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StockFrameCoin5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StockFrameCoin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StockFrameCoin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StockFrameCoin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StockFrameCoin2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(RestockButton))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {StockFrameCoin1, StockFrameCoin2, StockFrameCoin3, StockFrameCoin4, StockFrameCoin5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(StockFrameGun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(StockFrameGun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(StockFrameGun3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StockFrameGun4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(StockFrameGun5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StockFrameCoin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(StockFrameGun6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(StockFrameCoin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockFrameCoin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockFrameCoin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockFrameCoin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RestockButton)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {StockFrameGun1, StockFrameGun2, StockFrameGun3, StockFrameGun4, StockFrameGun5, StockFrameGun6});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {StockFrameCoin1, StockFrameCoin2, StockFrameCoin3, StockFrameCoin4, StockFrameCoin5});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        N7Vending frame2 = new N7Vending();//this line of code links the form window from the N7Vending form to this form window.
        
        StockFrameGun1.setText(String.valueOf(frame2.WeaponStock1));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameGun2.setText(String.valueOf(frame2.WeaponStock2));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameGun3.setText(String.valueOf(frame2.WeaponStock3));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameGun4.setText(String.valueOf(frame2.WeaponStock4));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameGun5.setText(String.valueOf(frame2.WeaponStock5));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameGun6.setText(String.valueOf(frame2.WeaponStock6));//This line pulls information of weapon stock in from the form window in the main vending machine.
        
        StockFrameCoin1.setText(String.valueOf(frame2.EuroStock2));//This line pulls information of coin stock in from the form window in the main vending machine.
        StockFrameCoin2.setText(String.valueOf(frame2.EuroStock1));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameCoin3.setText(String.valueOf(frame2.CentStock50));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameCoin4.setText(String.valueOf(frame2.CentStock20));//This line pulls information of weapon stock in from the form window in the main vending machine.
        StockFrameCoin5.setText(String.valueOf(frame2.CentStock10));//This line pulls information of weapon stock in from the form window in the main vending machine.
    }//GEN-LAST:event_formWindowOpened

    private void RestockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestockButtonActionPerformed
        GunToRestock1=Integer.parseInt(StockFrameGun1.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun1.setText(GunToRestock1+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        GunToRestock2=Integer.parseInt(StockFrameGun2.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun2.setText(GunToRestock2+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        GunToRestock3=Integer.parseInt(StockFrameGun3.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun3.setText(GunToRestock3+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        GunToRestock4=Integer.parseInt(StockFrameGun4.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun4.setText(GunToRestock4+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        GunToRestock5=Integer.parseInt(StockFrameGun5.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun5.setText(GunToRestock5+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        GunToRestock6=Integer.parseInt(StockFrameGun6.getText());//this line gets the updated value from the text field of the corrisponding weapon text field.
        StockFrameGun6.setText(GunToRestock6+"");//this line sets the text value gotten from the code above this line back into the main vending machine.

        CoinToRestock1=Integer.parseInt(StockFrameCoin1.getText());//this line gets the updated value from the text field of the corrisponding coin text field in the restock form.
        StockFrameCoin1.setText(CoinToRestock1+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        CoinToRestock2=Integer.parseInt(StockFrameCoin2.getText());//this line gets the updated value from the text field of the corrisponding coin text field in the restock form.
        StockFrameCoin2.setText(CoinToRestock2+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        CoinToRestock3=Integer.parseInt(StockFrameCoin3.getText());//this line gets the updated value from the text field of the corrisponding coin text field in the restock form.
        StockFrameCoin3.setText(CoinToRestock3+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        CoinToRestock4=Integer.parseInt(StockFrameCoin4.getText());//this line gets the updated value from the text field of the corrisponding coin text field in the restock form.
        StockFrameCoin4.setText(CoinToRestock4+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        CoinToRestock5=Integer.parseInt(StockFrameCoin5.getText());//this line gets the updated value from the text field of the corrisponding coin text field in the restock form.
        StockFrameCoin5.setText(CoinToRestock5+"");//this line sets the text value gotten from the code above this line back into the main vending machine.
        

       setVisible(false);//this line and the one below close the restock window.
       dispose();

       N7Vending Frame1 = new N7Vending();//this line and the one below open the Maine vending machine.
       Frame1.setVisible(true);
    }//GEN-LAST:event_RestockButtonActionPerformed

    private void StockFrameGun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockFrameGun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockFrameGun1ActionPerformed

    private void StockFrameCoin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockFrameCoin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StockFrameCoin1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestockForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RestockButton;
    private javax.swing.JTextField StockFrameCoin1;
    private javax.swing.JTextField StockFrameCoin2;
    private javax.swing.JTextField StockFrameCoin3;
    private javax.swing.JTextField StockFrameCoin4;
    private javax.swing.JTextField StockFrameCoin5;
    private javax.swing.JTextField StockFrameGun1;
    private javax.swing.JTextField StockFrameGun2;
    private javax.swing.JTextField StockFrameGun3;
    private javax.swing.JTextField StockFrameGun4;
    private javax.swing.JTextField StockFrameGun5;
    private javax.swing.JTextField StockFrameGun6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
